#!/bin/sh
cd ..
make clean
make
cd hack
rm *.s
cp ../kernel/l2/*.s .
cp ../build/*.s .
./clean
./dupsto
./build
./link
cd ../build
objcopy -I elf32-little -O binary -j .text -j .rodata a.out a.img
cd -

